language: php
php:
  - 5.5
  - 5.4
before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
script: phpunit --coverage-text --configuration . .