language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - composer self-update

install:
  - composer install --prefer-source

script: vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 5.4
    - php: 7.0